- name: app-setup
  ansible.builtin.import_role:
        name: common
        tasks_from: app-setup.yaml
- name: install nodejs
  ansible.builtin.import_role:
        name: common
        tasks_from: nodejs.yaml


- name: Copy user service file
  ansible.builtin.copy:
    src: user.service
    dest: /etc/systemd/system/user.service

- name: start and enable  the service
  ansible.builtin.service:
      name: user
      enabled: yes 
      state: started
      daemon_reload: true