- name: app-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: install dependencies
  ansible.builtin.import_role:
        name: common
        tasks_from: python.yaml
        
- name: restart the service
  ansible.builtin.import_role:
      name: common
      tasks_from: system-setup.yaml
