- name: create system user
  ansible.builtin.user:
    name: roboshop
    comment: system user
    system: true
    shell: /sbin/nologin
    home: /app
# safe to remove the directory, because when we run 2 time it will consider the previously downloaded file though the file have new chnages it doesnot download new one
- name: remove app directory if exits
  ansible.builtin.file:
    path: /app
    state: absent

- name: craete app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Delete the previously downloaded file
  ansible.builtin.file:
    path: /tmp/{{ component }}.zip
    state: absent

- name: download the application code
  ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip 
      dest: /tmp/{{ component }}.zip

- name: unzip the file into app directory
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /app
    remote_src: yes