 - name: disable nodejs previous version
   ansible.builtin.command: dnf module disable nodejs -y
  
 - name: enable required version
   ansible.builtin.command: dnf module enable nodejs:20 -y
  
 - name: install nodejs 
   ansible.builtin.package:
      name: nodejs 
      state: present
      
 - name: install npm 
   community.general.npm:
     path: /app
     